version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
    - 0.24.1
  - dependency-name: amqp
    versions:
    - 1.6.0
    - 2.0.0
    - 2.1.0
  - dependency-name: excoveralls
    versions:
    - 0.13.4
  - dependency-name: ex_check
    versions:
    - 0.13.0
  - dependency-name: credo
    versions:
    - 1.5.4
