name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    env:
      MIX_ENV: test

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3
        ports:
          - 5672:5672

    strategy:
      matrix:
        elixir-version: ['1.9', '1.10']
        otp-version: ['22.2']

    steps:
    - uses: actions/checkout@v2
    - name: Use Elixir ${{ matrix.elixir-version }}
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}

    - name: Install Dependencies
      run: mix deps.get

    - name: Check code formatting
      run: mix format --check-formatted

    - name: Compile source
      run: mix compile

    - name: Run Tests
      run: mix test

    # - name: Produce test coverage
    #   run: mix coveralls.xml

    # - run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
    #   env:
    #     CI: true
    #     CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
