name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3
        ports:
          - 5672:5672

    strategy:
      matrix:
        elixir-version: ['1.9', '1.10']
        otp-version: ['22.2']

    steps:
    - uses: actions/checkout@v2
    - name: Use Elixir ${{ matrix.elixir-version }}
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}

    - name: Install Dependencies
      run: mix deps.get

    - name: Check code formatting
      run: mix format --check-formatted

    - name: Compile source
      run: mix compile

    - name: Run tests and publish test coverage
      run: mix coveralls.github
      # env:
      #   COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
