name: Build and publish a Hex package

on:
  push:
    tags:
      - v*

jobs:
  publish:

    env:
      MIX_ENV: test

    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3
        ports:
          - 5672:5672

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.9'
        otp-version: '22.2'

    - name: Install Dependencies
      run: mix deps.get

    - name: Check code formatting
      run: mix format --check-formatted

    - name: Compile source
      run: mix compile

    - name: Run Tests
      run: mix test

    - name: Build package
      run: mix hex.build
      env:
        MIX_ENV: dev

    - name: Publish package
      run: mix hex.publish --yes
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        MIX_ENV: dev
